### ISSUE TITLE
Nothing happens on run

### ISSUE THREAD

**Issue by Bton123** [sebheron/TikTokLiveSharp#11]
Currently running this code under a game object with no errors, but also 0 response in the console:

using System.Collections;
using System.Collections.Generic;
using TikTokLiveSharp.Client;
using TikTokLiveSharp.Errors;
using TikTokLiveSharp.Events;
using TikTokLiveSharp.Protobuf;
using UnityEngine;

public class TikTokLive : MonoBehaviour
{
    private static TikTokLiveClient client;
    private void Start()
    {
        SetupTikTok();
    }
    private void SetupTikTok()
    {
        client = new TikTokLiveClient("skivur"); //user was live at the time of testing
        client.OnCommentRecieved += Client_OnCommentRecieved;
    }
    public void StartListening()
    { // triggered by clicking on a button in the scene UI
        client.Start();
    }
    private static void Client_OnCommentRecieved(object sender, WebcastChatMessage e)
    {
        string s = $"{e.User.uniqueId}: {e.Comment}";
        Debug.Log(s);
    }
}

Im fairly new to programming, so if im missing something significant i wouldnt be suprised. i imported the unitypackage with the 2 dlls into my assets folder... is there anything else I need to do to get the script to run?

**Comment by brogrammer1337** [comment]
Unfortunately, this repository no longer works here. The NodeJS variant works.
I think this is unfortunately no longer being worked on.

**Comment by sebheron** [comment]
I know it seems like that, but I'm currently in the process of upgrading the project.
I've run into some issues with the WebSockets that .NET uses, but I'm aiming to get a release out within the next few weeks.

**Comment by sebheron** [comment]
I've updated the package.

**Comment by Bton123** [comment]
preciate u dawg

**Comment by sebheron** [comment]
No worries 😂, fingers crossed TikTok don't update anytime soon 🤞
