### ISSUE TITLE
Follow not working, bunch of errors

### ISSUE THREAD

**Issue by Bton123** [sebheron/TikTokLiveSharp#13]
Are there any blatant mistakes? I tried changing the event handler, 
public class TikTokFollow: MonoBehaviour
{
    public string uniqueID;

    void Start()
    {
        var client = new TikTokLiveClient(uniqueID);
        client.OnFollow += Client_OnFollow;
        client.Start();
    }

    private void Client_OnFollow(object sender, pm_main_follow_message_viewer_2 e) 
                 
    {
        Debug.Log($"{e.User.uniqueId}: {e.Comment}");
    }
}

**Comment by sebheron** [comment]
"pm_main_follow_message_viewer_2" should not be the event type. Try deleting the method "Client_OnFollow" and let Visual Studio build it for you.

**Comment by JosueR2** [comment]
Hi, the ChatExample script works but just for 1 or 2 seconds then stops, no errors in console and maybe 10 comments but no more, how do I make the script continue reading the comments?

**Comment by Bton123** [comment]
> 

Ty for the response, wdym build? Like intellisense?

**Comment by Akanthor** [comment]
> Hi, the ChatExample script works but just for 1 or 2 seconds then stops, no errors in console and maybe 10 comments but no more, how do I make the script continue reading the comments?

Same problem for me, the initial code works fine in Application Console. But in Unity the same code with simple modifications to fit with the environment runs 2 sec before stop.

I had the same issue before and my solution was to reintegrate Flurl but with the new auth system i don't have enough skill to make it work again

**Comment by sebheron** [comment]
@JosueR2 @Akanthor try the new example in v0.1.4 and build off of that.

@Bton123 Yep

**Comment by Akanthor** [comment]
> @JosueR2 @Akanthor try the new example in v0.1.4 and build off of that.
> 
> @Bton123 Yep

@sebheron  Thank for your update, unfortunatly i have the same problem with Unity
I tried with both method (Start and Run who sometimes crashed Unity)
I received messages for 1 frame and it stops immediately

Thank you again for your help

```
public class test : MonoBehaviour
{
    public string id;
    private TikTokLiveClient client;

    void Start()
    {
        client = new TikTokLiveClient(id);

        client.OnCommentRecieved += Client_OnCommentRecieved;

        client.Start(new System.Threading.CancellationToken());
    }

    private void Client_OnCommentRecieved(object sender, TikTokLiveSharp.Models.WebcastChatMessage e)
    {
        Debug.Log("Comment received");
    }
}
```

![Capture](https://user-images.githubusercontent.com/111450485/185224880-8e3c749e-7f6c-4683-bd6a-cee082cb16b8.JPG)

**Comment by sebheron** [comment]
@Akanthor Build off of the example script

**Comment by Akanthor** [comment]
@sebheron  When you speak about example script, you refer to Program.cs ? Because i can't build of  this because it doesn't inherits of Monobehaviour

Sorry to bother you again i feel so dumb

**Comment by sebheron** [comment]
@Akanthor It's okay. I'm referring to the Example.cs file in the unity package found [here](https://github.com/sebheron/TikTokLiveSharp/releases/tag/v0.1.4).

**Comment by Akanthor** [comment]
@sebheron  OMGG i'm going to test it immediatly, i'm sure it will works ! Thank you again for your work !

**Comment by Akanthor** [comment]
@sebheron  I've tested with the last version of Example.cs and it's the same problem it's catching messages for 1 frame and stops without any error

**Comment by JosueR2** [comment]
@Akanthor @sebheron thanks, now the script works continuously, just create a new proyect with unity 2021.3 and done, but  my script dont read the likes, "OnLikesRecieved" works, but "OnLike" dont,
I already tried with comments, gifts and sharing, and no problem

    public void Start()
    {
        _client = new TikTokLiveClient(id);
        _profilePictures = new Queue<string>();
        _client.OnCommentRecieved += Client_OnCommentRecieved;
        _client.OnLike += Client_OnLike;
        _client.OnLikesRecieved -= Client_OnLikeRecieved;
        try
        {
            _client.Start();
        }
        catch (System.Exception e)
        {
            Debug.LogException(e);
        }
    }

    void Client_OnLike(object sender, User e)
    {
        Debug.Log($"{e.uniqueId}: !!!!!!!!! LIKE !!!!!!!!!!");
    }

**Comment by Bton123** [comment]
> @Akanthor @sebheron thanks, now the script works continuously, just create a new proyect with unity 2021.3 and done, but my script dont read the likes, "OnLikesRecieved" works, but "OnLike" dont, I already tried with comments, gifts and sharing, and no problem
> 
> ```
> public void Start()
> {
>     _client = new TikTokLiveClient(id);
>     _profilePictures = new Queue<string>();
>     _client.OnCommentRecieved += Client_OnCommentRecieved;
>     _client.OnLike += Client_OnLike;
>     _client.OnLikesRecieved -= Client_OnLikeRecieved;
>     try
>     {
>         _client.Start();
>     }
>     catch (System.Exception e)
>     {
>         Debug.LogException(e);
>     }
> }
> 
> void Client_OnLike(object sender, User e)
> {
>     Debug.Log($"{e.uniqueId}: !!!!!!!!! LIKE !!!!!!!!!!");
> }
> ```

Have you tried OnFollow? If so, did u need an eventhandler? Im trying to use WebcastSocialMessage but no avail.

**Comment by JosueR2** [comment]
@Bton123 this work

    client.OnFollow += Client_OnFollow;

    private static void Client_OnFollow(object sender, User e)
    {
        Debug.Log($"{e.uniqueId}: !!!!!!!!!! FOLLOW !!!!!!!!!");
    }

**Comment by sebheron** [comment]
There's probably an issue with likes that'll have to get around to fixing. Until now I'll close this, I can promise it'll be sorted asap 😄

**Comment by AndrewXB** [comment]
Ohp I see that this issue is still on going. Is there any progress on it?

**Comment by MrPatryk** [comment]
Problem with OnLike i still here, any feedback?
