### ISSUE TITLE
No longer receiving data from TikTok

### ISSUE THREAD

**Issue by itspixelfire** [sebheron/TikTokLiveSharp#16]
@sebheron Everything was working just fine for me. TikTokLiveSharp was pulling comments and such from TikTok.
But all of a sudden it's not working.
I've backtracked all my code to a time when I know it was working, and even ran your new Example script by itself.
No data from TikTok anymore.

Is it possible TikTok would blacklist my IP and prohibit my IP from searching their site?
Would that even affect TikTokLiveSharp from working?

Or do you suspect something else is at play here? (Maybe Start/Stop Listening still existing on threads and competing with new instances? Wouldn't even know how to check if they were).

**Comment by Bton123** [comment]
Idk if this is related, but simply running the example.cs script seems to do nothing, like its not running.

**Comment by sebheron** [comment]
Ah this could be a problem.
I'll have to look into it.

**Comment by Bton123** [comment]
> Ah this could be a problem. I'll have to look into it.

I take it back, reimported and running smoothly.!

**Comment by itspixelfire** [comment]
@sebheron What do you suspect is the issue?
Also, have you considered setting up a Discord? We could more easily chat and provide quicker feedback.

**Comment by sebheron** [comment]
@itspixelfire Part of the general TikTok live connector library that this is based on, requires a signature to be generated from an endpoint on Isaac Kogan's server and it just quickly went offline and then like magic, started working again. I did have a moment of worry where I thought I'd missed something in the translation which TikTok flagged, but it seems like everything is ok 🤞.

There's no Discord, but there is a Gitter community you can post in. I know both Isaac and Zerody have Discord servers and for anything non C# related, they could offer better advice for anyways.

**Comment by itspixelfire** [comment]
Still having issues with this.
