### ISSUE TITLE
Only receiving data for a few seconds

### ISSUE THREAD

**Issue by itspixelfire** [sebheron/TikTokLiveSharp#18]
Still running into a problem where I'm only receiving data for a few seconds.
Even using the Example.cs you provided, as is. Cubes with profile pictures will spawn in for a few seconds, and then stop.
The same applies for comments and likes.
I'll press stop, press play again, and it'll work for a few seconds and then stop.
Any idea why it stops working after a few seconds? Could this be TikTok blocking us? Or maybe an issue with the new "models"? Things were running flawlessly for me when we were using protobuf.

**Comment by JosueR2** [comment]
Use unity 2021.3 or higher

**Comment by itspixelfire** [comment]
@JosueR2 Thanks, I'll try that.
Is there a reason though? What does 2021.3 add that the previous versions don't have that allows TTLS to work?

**Comment by itspixelfire** [comment]
Using 2021.3.9 now, and still having the same problem.

**Comment by cesar-ioc** [comment]
Did you manage to solve this? I´m also having the same problem, it only receives events for like 5 seconds after running it and then stops
