### ISSUE TITLE
Stopped working completely

### ISSUE THREAD

**Issue by raszop** [sebheron/TikTokLiveSharp#26]
I have had successful run with this for about 2 days and now it doesnt work at all. I have tried everything including windows defender settings, rewriting code, downgrading to 1.3, and even went to chat to read that if the sample chat project works than plugin should work properly, but it doesnt. it doesnt react to any events i used OnLikesReceived and it worked now it doesnt. OnCommented not working either.

**Comment by raszop** [comment]
works again. i cant thank you enough for this

**Comment by cooldude3828** [comment]
> works again. i cant thank you enough for this

YAY!!
