### ISSUE TITLE
Code Hangs in Unity

### ISSUE THREAD

**Issue by sanboxapps** [sebheron/TikTokLiveSharp#5]
Hello, 
Thanks for converting the tik tok sdk to unity, I can't wait to start using it.
However anytime I try to execute the run command, unity hangs.
I tried this on Unity 2022.1.1f and Unity 2021.3.5f LTS

```
public class TikTokLive : MonoBehaviour {
  private static TikTokLiveClient client;
  private void Start() {
      setupTikTok();
  }
  private void setupTikTok() {
      client = new TikTokLiveClient("manifestationmomma"); //user was live at the time of testing
      client.OnCommentRecieved += Client_OnCommentRecieved;
  }
  public void startListening() { // triggered by clicking on a button in the scene UI
      client.Run();
  }
  private static void Client_OnCommentRecieved(object sender, WebcastChatMessage e) {
      string s = $"{e.User.uniqueId}: {e.Comment}";
      Debug.Log(s);
  }
}
```
I have tested the code as a Stand alone c# project and it works, just not when inside Unity.
Any pointers would be greatly appreciated.

**Comment by itspixelfire** [comment]
I second this. Help would be appreciated!

**Comment by sebheron** [comment]
I'll check it today and try and get it working.

**Comment by sebheron** [comment]
Alright so, when using Unity you're going to want to use TikTokLiveClient's Start method (instead of Run) to prevent blocking. Try that and let me know if it works.

**Comment by itspixelfire** [comment]
That works, thanks a lot! :) One more question...What exactly is Protobuf? And does it really need to be used?
Just wondering if there's a simpler way for TikTokLiveSharp to be coded, but maybe I'm completely wrong?

**Comment by Skytrymotion** [comment]
Whats the difference between Start() and Run()?

**Comment by sebheron** [comment]
> That works, thanks a lot! :) One more question...What exactly is Protobuf? And does it really need to be used?
> 
> Just wondering if there's a simpler way for TikTokLiveSharp to be coded, but maybe I'm completely wrong?

Protobufs are a serialised data structure, used for fast communication of data. Protobuf-net parses this data for us, without the need for anyone to spend time parsing the data themselves. Parsing it isn't supported in vanilla .NET, so the library saves a lot of time and legwork.

**Comment by sebheron** [comment]
> Whats the difference between Start() and Run()?
> 
> 

I'll point you towards here [https://github.com/isaackogan/TikTokLive](https://github.com/isaackogan/TikTokLive) for all documentation related questions (most of the methods are the same). Run() will block the program, meaning that the application will stop on that specific line, and Start() runs the client asynchronously on a separate thread.
