### ISSUE TITLE
OnJoin not working

### ISSUE THREAD

**Issue by AlexEnse** [sebheron/TikTokLiveSharp#6]
Hello ;)

Did you check the OnJoin event? Looks like it's not work.

**Comment by HakkanR** [comment]
add code below to swict case of private void InvokeEvent(Message message) in TikTokLiveClient.cs 
`                  case nameof(WebcastMemberMessage):
                        var memberMessage = ProtoBuf.Serializer.Deserialize<WebcastMemberMessage>(stream);
                        if (OnJoin != null)
                            this.OnJoin.Invoke(this, memberMessage);
                        return;`

add code below to Main of program.cs
`client.OnJoin += Client_OnJoin;`

and last add this eventhandler function to out of Main
` private static void Client_OnJoin(object sender, WebcastMemberMessage e)
        {
            Console.WriteLine($"[JOIN] {e.User.uniqueId}");
        }`

**Comment by thekurdmaker** [comment]
> add code below to swict case of private void InvokeEvent(Message message) in TikTokLiveClient.cs ` case nameof(WebcastMemberMessage): var memberMessage = ProtoBuf.Serializer.Deserialize<WebcastMemberMessage>(stream); if (OnJoin != null) this.OnJoin.Invoke(this, memberMessage); return;`

can you show a screen shot for this part , i donot know where to add this code exaclty !?

**Comment by sebheron** [comment]
I've got some time now, I'll give this a look.
@HakkanR cheers for supplying that snippet.

**Comment by sebheron** [comment]
I'm going to assign this for the next update. I got bogged down with trying to get legacy usage fixed, this is next on the list.

**Comment by sebheron** [comment]
OnJoin should be fixed as of #15
