### ISSUE TITLE
Profile Pic in Unity

### ISSUE THREAD

**Issue by itspixelfire** [sebheron/TikTokLiveSharp#9]
Having some trouble getting a user's profile picture to show up as a texture in Unity.
Does TikTokLiveSharp provide the image? Or just the URL?

Confused how to display a profile pic as a texture in Unity.

**Comment by JosueR2** [comment]
Hi, please can you help me to get this work? I get null reference on unity
![image](https://user-images.githubusercontent.com/56123888/180615855-b72c22d4-67fd-4d5e-9309-e7f2a9acea24.png)

**Comment by sebheron** [comment]
You're going to want use to the "Start" method for the TikTokLiveClient.
Images might not be in the right format, I'm looking into this atm.

**Comment by itspixelfire** [comment]
Hi @sebheron! What closed this exactly?
Was it this? -> https://github.com/sebheron/TikTokLiveSharp/commit/3920cc0ff5a4f47a5557383d2c3086a7bbdf1488

Do profile pics work now?

**Comment by sebheron** [comment]
It's unlikely I'll implement a download feature for images directly, although in Unity you can pass the .JPEG url from "profilePicture.Urls" into a UnityWebRequest and build a texture that way.

**Comment by itspixelfire** [comment]
@sebheron Okay.
I've had success doing that with other APIs, and tried to do so with this one, but wasn't able to get it to work.
I understand it's outside the scope of what you're wanting to implement. But is there any chance you could write up a small script for me that accomplishes this?
I'm totally willing to pay you for your time :)

**Comment by sebheron** [comment]
@itspixelfire I've just published a new package with an example I'm sure you'll appreciate

**Comment by itspixelfire** [comment]
@sebheron You're the best! Thanks so much! Curious question, why have we switched from Protobuf to Models?

**Comment by itspixelfire** [comment]
Nice!
